environment:
  VisualStudioVersion: 12.0

platform:
  - Any CPU

configuration:
  - Release

install:
  - Invoke-WebRequest "https://stylecop.codeplex.com/downloads/get/323236" -OutFile ./StyleCopInstaller.msi
  - .\StyleCopInstaller.msi /quiet

before_build:
  - nuget restore