environment:
  VisualStudioVersion: 12.0

platform:
  - Any CPU

configuration:
  - Release

install:
  - ps: Invoke-WebRequest "https://stylecop.codeplex.com/downloads/get/323236" -OutFile "StyleCopInstaller.msi"
  - ps: Start-Process .\StyleCopInstaller.msi /quiet -Wait

before_build:
  - nuget restore