environment:
  VisualStudioVersion: 12.0

platform:
  - Any CPU

configuration:
  - Release

install:
  - ps: (new-object net.webclient).DownloadFile('https://stylecop.codeplex.com/downloads/get/323236', 'StyleCopInstaller.msi')
  - ps: msiexec /i StyleCopInstaller.msi /quiet /qn /norestart /log install.log

before_build:
  - nuget restore